### ISSUE TITLE
Verify historical summaries in step circuit

### ISSUE THREAD

**Issue by nulltea** [ChainSafe/Spectre#60]
Having historical summaries root in the step circuit's public inputs would allow for more ways to verify transaction inclusion in Eth1 via cost-effective event (receipt trie) proofs.

To enable this, the Step circuit must be extended with another Merkle proof from historical summaries root to beacon state_root (a part of the attested header). The verified historical summaries root must be added to public inputs.

**Comment by itsbobbyzzz168** [comment]
“Receipt proofs for cost-optimisation” will be covered in Spectre x Axiom integration, Axiom already support this so this ticket can be flagged as “not going to do”
